# Generated by Django 4.0.5 on 2022-07-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='family',
            field=models.CharField(default='', editable=False, max_length=150),
        ),
    ]
