# Generated by Django 4.0.5 on 2022-07-27 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note_app', '0002_users_family'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Users_model',
        ),
    ]
