# Generated by Django 4.0.5 on 2022-07-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_app', '0003_rename_users_users_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_model',
            name='family',
            field=models.CharField(default='', max_length=150),
        ),
    ]
